name: fedoo

channels:
  - conda-forge
  - set3mah

dependencies:
  - python=3.10
  - numpy>=1.24
  - scipy
  - pypardiso # [x86 or x86_64]
  # - scikit-umfpack # [(not x86) and (not x86_64)]
  - vtk>=9.2
  - pyvista>=0.39
  - simcoon>=1.9.6
  - pytest
  - sphinx_rtd_theme
  - sphinx-gallery
